name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        working-directory: ./server
        run: npm install
      - name: build project
        working-directory: ./server
        run: npm run build --if-present
      - name: unit test
        working-directory: ./server
        run: npm run test
      - name: e2e test
        working-directory: ./server
        run: npm run test:e2e
      - name: lint
        working-directory: ./server
        run: npm run lint